name = "LiveLayoutUnicodePlots"
uuid = "12914b07-88f0-4992-9f44-10eddbd465c9"
authors = ["Soeren Schoenbrod <soeren.schoenbrod@outlook.de>"]
version = "0.1.0"

[deps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
julia = "1.10"
UnicodePlots = "3"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Test"]
